# Generated by Django 5.1.3 on 2024-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="begin_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="period",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
