# Generated by Django 5.1.3 on 2024-12-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_leaveapplication_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.semester",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
