# Generated by Django 5.1.3 on 2024-12-05 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_course_day_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="guardian_id",
            field=models.CharField(
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
