# Generated by Django 5.1.3 on 2024-12-09 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_guardian_student_alter_guardian_guardian_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.PositiveIntegerField(
                help_text="請輸入年份，例如 2024",
                validators=[django.core.validators.MinValueValidator(1900)],
            ),
        ),
    ]
