# Generated by Django 5.1.3 on 2024-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_semester_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eng_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
