# Generated by Django 5.1.3 on 2024-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_user_eng_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="relationship",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="type_name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="eng_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
